### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by matteyeux** [0x7ff/golb#2]
Hey, 

I'm wondering if with or `aes_ap` or `key_dumper` it is possible to grab firmware keys for bootloaders. 

Also when running `aes_ap` I don't get what has to be the input or the output. Does it have to be a file ?  What type of file ?

Could you please explain the purpose of these tools please ?

Thank you.

**Comment by 0x7ff** [comment]
Hey matteyeux,
Yes, it's possible to decrypt KBAG(s) with aes_ap if the hardware AES GID engine is unlocked (the latest version of checkra1n (0.10.2) should unlock the GID key). If you don't provide any arguments for aes_ap, it should print the special UID keys used for keychain stuff and nonce entanglement. Otherwise, the usage for decrypting KBAG(s) is "./aes_ap dec GID0 KBAG_in KBAG_out 48" (KBAG_in is the file with KBAG(s) in raw binary format, 48 is the size of the IVkey). On older versions, it supported only one KBAG decryption per execution, which was pretty slow due to kernel decompression routine. Starting with A12, you can't change page table entries (PTE) due to PPL (Page Protection Layer). However, you can dump special UID keys from IOAESAccelerator using key_dumper. Which is useful with dimentio as it calculates the entangled_nonce, so you don't have to reboot for saving blobs (or you can verify if its working).

**Comment by matteyeux** [comment]
Hi,

thank you for replying to my questions, it seems a bit clearer right now :).

About PPL, Brandon Azad just published a method to bypass : https://bugs.chromium.org/p/project-zero/issues/detail?id=2035.

**Comment by 0x7ff** [comment]
Hey matteyeux,
Thanks for sharing, it's great to see public PPL bypasses. However, PPL is not an issue as most of the IO mappings do not have the PP_ATTR_MONITOR attribute nor the PVH_FLAG_LOCKDOWN flag. So you can get virtual addresses for AES_AP_BASE_ADDR and PMGR_SECURITY_BASE_ADDR just by looking inside the IOAESAccelerator object (at offset 0x168 and 0x178 respectively). Then you can map to userspace just by calling mach_vm_remap. As for the checkra1n issue, I think there is an issue with AOP (Always On Processor) reconfig patches (for older devices this issue does not exist as it lacks AOP but you must not enter deep sleep if you want to use the GID keys (0x3E8 and 0x3E9)). It patches the platform_disable_keys call inside iBoot, but without the patch for AppleS8000AESAccelerator::disableHardwareKey, you must go into deep sleep to enable the GID keys. However, the issue still persists after going into deep sleep, so this is why I think AOP reconfig patches is the issue. However, the AOP reconfig engine is unlocked with checkra1n so you can patch it manually after the boot.

**Comment by matteyeux** [comment]
Alright, thank you for your time and explaining stuff I did not understood !
I can close issue as everything is clear right now :)
